<div class="weui-search-bar" id="searchBar">
    <form class="weui-search-bar__form" method="get" action="/category/search.html">
        <div class="weui-search-bar__box">
            <i class="weui-icon-search"></i>
            <input type="search" name="keywords" class="weui-search-bar__input" id="searchInput" placeholder="搜索" value="<?=$keywords?>">
            <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
        </div>
        <label class="weui-search-bar__label" id="searchText">
            <i class="weui-icon-search"></i>
            <span>搜索“<span class="red"><?=$keywords?></span>”的结果</span>
        </label>
    </form>
    <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
</div>
<div class="weui-tab__bd-item weui-tab__bd-item--active">
    <div class="weui-panel weui-panel_access index-list">
        <div class="weui-panel__hd"><?= $catrgoryName ?></div>
        <div class="weui-panel__bd">
            <?php if (!empty($data)):foreach ($data as $val): ?>
                <a href="/book/index.html?id=<?= $val['id'] ?>" class="weui-media-box weui-media-box_appmsg">
                    <div class="weui-media-box__hd">
                        <img class="weui-media-box__thumb" src="<?= $val['book_img'] ?>">
                    </div>
                    <div class="weui-media-box__bd">
                        <p class="weui-media-box__desc title"><?= $val['book_name'] ?></p>
                        <p class="weui-media-box__desc">作者：<?= $val['book_author'] ?></p>
                        <p class="weui-media-box__desc">摘要：<?= $val['book_intro'] ?></p>
                    </div>
                </a>
            <?php endforeach;?>
            <?php else:?>
                <div style="text-align: center;padding: 20px 0">暂时结果</div>
            <?php endif; ?>
        </div>
        <?php if (!empty($data)):?>
        <div class="weui-panel__bd">
            <div class="page">
                <?php if ($page > 1):?>
                <a href="?id=<?=$categoryId?>&page=<?=($page - 1)?>" class="weui-btn weui-btn_mini weui-btn_plain-primary weui-btn_disabled">上一页</a>
                <?php endif;?>
                <span class="weui-btn weui-btn_mini"><?=$page?> / <?=$pageTotal?></span>
                <?php if ($page < $pageTotal):?>
                <a href="?id=<?=$categoryId?>&page=<?=($page + 1)?>" class="weui-btn weui-btn_mini weui-btn_plain-primary weui-btn_disabled">下一页</a>
                <?php endif;?>
            </div>
        </div>
        <?php endif;?>
    </div>
</div>
<script>
    $(function () {
        $(document.body).infinite();
    });
</script>