<div class="weui-flex nav-top" style="opacity: 1;position: relative;">
    <div class="weui-flex__item"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAABmCAMAAACtKXKWAAAAn1BMVEUAAADm5uZERER3d3eHh4c9PT0zMzNAQEA2Njbw8PD7+/tPT09GRkb9/f2rq6uQkJBLS0v09PTr6+vp6enh4eHc3NzT09PPz8/ExMS4uLidnZ2CgoJqampfX19bW1tTU1M7Ozv29vbX19dmZmY9PT1XV1f4+Pj39/fJycm+vr6ysrKkpKSXl5eIiIh7e3t2dnZ1dXVvb285OTlWVlbZ2dnTs/viAAAABnRSTlMA/vz8/PzlztqAAAABjklEQVRYw9WY127CQBBFjUnWDVzo1abY9A7//21RlISd12NFC77vR7Lg7p7ZsXiaYZpn0dziSZbqO0GCSS9VP/mgZDtTv4kh2YnVX2xGLhrqmToi+44mnRohBzNB9gg5dDXZ6BIyFGSAvnakdIoWISNBTj1S27EgJ6S+/lmQFx+Q64kgx01S+KkgIwukVQhyRMhaIMiQkF1ReHdIyJ4o/GxAyE0uCt8n5PamSXtByJ0ofNwh5F7pZG1CHgSZeoQ8CnKZkMKfBHldAXJ1FeTJZ27QOUI36BygG3T2Jd2g3B1yg63J27asG/LN27tBVdYNa0D6F0GeSeHnr3DD/T/c4L69G2oOcoNMXRT+YaHY0g0sn8+jAtwAUPDB/GcCCgV/DqwEL6KB+oNDh486v2BMXGv8MuVXOBcH15UJSXI184GAjyF8+DEycvFBj4+XfKjlo7SJAZ4/G/hjhT+R+MOMPQerbRVFrVIYtApfafBFCl/fmLfKnVrFrbZVHPjND7z45OtWvuTlq2W+0C6/Rv8CppA3o4Rd7ncAAAAASUVORK5CYII=" class="back"></div>
    <div class="weui-flex__item title">个人资料</div>
    <div class="weui-flex__item home"><a href="/"><i class="fa fa-home"></i></a></div>
</div>
<header class='username-header'>
    <h1 class="username-title"><?=$user['username']?></h1>
</header>
<div class="weui-cells weui-cells_form">
    <div class="weui-cell">
        <div class="weui-cell__hd"><label class="weui-label">用户名</label></div>
        <div class="weui-cell__bd">
            <?=$user['username']?>
        </div>
    </div>
    <div class="weui-cell">
        <div class="weui-cell__hd"><label class="weui-label">最后登录IP</label></div>
        <div class="weui-cell__bd">
            <?=$user['last_ip']?>
        </div>
    </div>
    <div class="weui-cell">
        <div class="weui-cell__hd"><label class="weui-label">最后登录时间</label></div>
        <div class="weui-cell__bd">
            <?=$user['last_time']?>
        </div>
    </div>
    <div class="weui-btn-area">
        <a class="weui-btn weui-btn_warn" href="javascript:" id="logout">退出</a>
    </div>
</div>
<script>
    $(function () {
        $('#logout').click(function () {
            $.ajax({
                url: '/member/logout',
                dataType: 'json', //服务器返回json格式数据
                type: 'GET', //HTTP请求类型
                timeout: 10000, //超时时间设置为10秒；
                headers: {
                    'token': localStorage.getItem('token')
                },
                success: function(res) {
                    if (res.code == 201) {
                        localStorage.removeItem('token');
                        window.location.href = '/';
                    } else if (res.code == 0) {
                        localStorage.removeItem('token');
                        window.location.href = '/';
                    } else {
                        $.toptip(res.msg, 'error');
                    }
                },
                error: function(xhr, type, errorThrown) {
                    $.toptip('系统错误', 'error');
                }
            });
        });
    });
</script>