<div class="here">当前位置:<a href="/">网站首页</a> &gt; <?=$category[$book['book_category']]?> &gt; <?=$book['book_name']?></div>
<div class="book">
    <div class="like right">
        <div class="title_bg">猜你喜欢</div>
        <ul>
            <?php if (!empty($likeBooks)):foreach ($likeBooks as $key => $val):?>
                <li class="<?php if ($key == 3)echo 'border_none';?>"><a href="/book/index.html?id=<?=$val['id']?>" target="_blank" title="<?=$val['book_name']?>"><img src="<?=$val['book_img']?>" width="84" height="112"/></a><span class="l1"><a href="/book/index.html?id=<?=$val['id']?>" target="_blank" title="<?=$val['book_name']?>"><?=$val['book_name']?></a></span><span class="l2"><?=$val['book_author']?></span><span class="l3"><a href="/book/index.html?id=<?=$val['id']?>" target="_blank"><?=mb_substr($val['book_intro'], 0, 60)?>...</a></span></li>
            <?php endforeach;endif;?>
        </ul>
    </div>
    <div class="info left">
        <p class="left"><img src="<?=$book['book_img']?>" width="168" height="224" /></p>
        <div class="book-info right">
            <h1><p class="author">作者：<?=$book['book_author']?></p><strong><?=$book['book_name']?></strong></h1>
            <p class="click"><i>·</i> <a href="/category/index.html?id=<?=$book['book_category']?>"><?=$category[$book['book_category']]?></a> <i>·</i> <?=$book['book_click']?>浏览  <i>·</i> <?=$book['book_wordsnumber']?>字数  <i>·</i> <?=$book['book_state'] == 1 ? '完本' : '连载'?></p>
            <p class="intro"><?=$book['book_intro']?></p>
            <p class="keywords">关键字：<?php if (!empty($book['book_keyword'])):foreach (explode(',', $book['book_keyword']) as $val):?><a href="javascript:;"><?=$val?></a><?php endforeach;endif;?></p>
            <div class="book_btn"><a href="/book/chapter.html?book_id=<?=$book['id']?>" class="btn btn-success">开始阅读</a><a href="javascript:void(0);" data-id="<?=$book['id']?>" <?=empty($userBook) ? '' : 'disabled'?> class="btn btn-default btn_sj"><?=empty($userBook) ? '加入书架' : '已在书架'?></a><!-- <a href="javascript:void(0);" class="btn_tj" onclick="post_recommend({$book.book_id})">投推荐票</a>--></div>
        </div>
    </div>
    <div class="lastnew left">
        <h3 class="title_bg"><?=$book['book_name']?>最新章节</h3>
        <dl>
            <?php if (!empty($article)):?>
            <dt><a href="/book/article.html?book_id=<?=$book['id']?>&id=<?=$article['id']?>" title="<?=$article['title']?>"><?=$article['title']?></a><span>(更新于: <?=$article['create_at']?>)</span></dt>
            <dd><?=mb_substr($article['content'], 0, 500)?>......</dd>
            <?php else:?>
            <dd>无</dd>
            <?php endif;?>
        </dl>
    </div>
    <div class="clear"></div>

</div>
<div class="clear"></div>
<script>
    $('.btn_sj').click(function () {
        let book_id = $(this).data('id');
        let obj = $(this);
        if (obj.attr('disabled')) {
            return false;
        }
        $.ajax({
            url: '/member/addBook?id='+book_id,
            dataType: 'json', //服务器返回json格式数据
            type: 'GET', //HTTP请求类型
            timeout: 10000, //超时时间设置为10秒；
            success: function(res) {
                if (res.code == 201) {
                    alertmsg('您未登录，请先登录');
                } else if (res.code == 0) {
                    alertmsg('加入成功');
                    obj.text('已在书架').attr('disabled', true);
                } else {
                    alertmsg(res.msg);
                }
            },
            error: function(xhr, type, errorThrown) {
                $.toptip('系统错误', 'error');
            }
        });
    });
</script>