<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $title ?></title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/dist/plugins/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/dist/css/info.css">
</head>
<body class="wap">

<div class="base">
    <div class="NovelDetail">
        <div id="Header" class="Header" style="opacity: 0;"><img
                    src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAABmCAMAAACtKXKWAAAAn1BMVEUAAADm5uZERER3d3eHh4c9PT0zMzNAQEA2Njbw8PD7+/tPT09GRkb9/f2rq6uQkJBLS0v09PTr6+vp6enh4eHc3NzT09PPz8/ExMS4uLidnZ2CgoJqampfX19bW1tTU1M7Ozv29vbX19dmZmY9PT1XV1f4+Pj39/fJycm+vr6ysrKkpKSXl5eIiIh7e3t2dnZ1dXVvb285OTlWVlbZ2dnTs/viAAAABnRSTlMA/vz8/PzlztqAAAABjklEQVRYw9WY127CQBBFjUnWDVzo1abY9A7//21RlISd12NFC77vR7Lg7p7ZsXiaYZpn0dziSZbqO0GCSS9VP/mgZDtTv4kh2YnVX2xGLhrqmToi+44mnRohBzNB9gg5dDXZ6BIyFGSAvnakdIoWISNBTj1S27EgJ6S+/lmQFx+Q64kgx01S+KkgIwukVQhyRMhaIMiQkF1ReHdIyJ4o/GxAyE0uCt8n5PamSXtByJ0ofNwh5F7pZG1CHgSZeoQ8CnKZkMKfBHldAXJ1FeTJZ27QOUI36BygG3T2Jd2g3B1yg63J27asG/LN27tBVdYNa0D6F0GeSeHnr3DD/T/c4L69G2oOcoNMXRT+YaHY0g0sn8+jAtwAUPDB/GcCCgV/DqwEL6KB+oNDh486v2BMXGv8MuVXOBcH15UJSXI184GAjyF8+DEycvFBj4+XfKjlo7SJAZ4/G/hjhT+R+MOMPQerbRVFrVIYtApfafBFCl/fmLfKnVrFrbZVHPjND7z45OtWvuTlq2W+0C6/Rv8CppA3o4Rd7ncAAAAASUVORK5CYII="
                    class="back">
            <h1 class="title"><?=$data['book_name']?></h1>
            <div class="bag">书包</div>
            <div class="detail-tab-wrap">
                <div class="detail-tab active" style="width: 25%;">简介</div>
                <div class="detail-tab" style="width: 25%;">预览</div>
                <div class="detail-tab" style="width: 25%;">互动</div>
                <div class="detail-tab" style="width: 25%;">推荐</div>
            </div>
        </div>
        <div class="detail-module-wrap">
            <div class="detail-header"><h1><?=$data['book_name']?></h1>
                <div class="detail-header-wrap">
                    <div class="detail-header-cont">
                        <div>
                            <div class="detail-header-cont-wrap-img"><img
                                        src="<?=$data['book_img']?>">
                            </div>
                            <div class="detail-header-cont-wrap-desc">
                                <div><span>作者：<?=$data['book_author']?></span></div>
                                <div class="detail-header-tags">
<!--                                    <div class="detail-header-tags-list"><span>男</span><span>玄幻</span><span>东方玄幻</span></div>-->
                                </div>
                                <div class="detail-header-status"><span><?php echo 1 === (int)$data['book_state'] ? '完本' : '连载'?></span> <span>约<?=round($data['book_wordsnumber']/10000, 2)?>万字</span>
                                </div>
                            </div>
                        </div>
                        <div class="detail-header-cont-wrap-opera">
                            <button data-log="addBag" class="detail-header-cont-wrap-opera-add">加入书包</button>
                            <button data-log="startRead" class="detail-header-cont-wrap-opera-read">开始阅读</button>
<!--                            <button data-log="offline" class="detail-header-cont-wrap-opera-down">-->
<!--                                离线下载-->
<!--                            </button>-->
                        </div>
                    </div>
                </div>
            </div>
        </div> <!---->
        <div class="detail-module-wrap detail-cont-wrap">
            <div class="detail-cont" status="连载" rankinfo="[object Object]" scoreavg="4.6" chapternum="5048"><!----> <p
                        class="detail-cont-desc textOverflow" style="-webkit-box-orient: vertical;">
                    <?=$data['book_intro']?></p>
                </div>
        </div> <!---->

        <div class="detail-category">
            <div class="detail-category-info"><span class="total-count">共<?=$count?>章</span>
<!--                <span class="sort-button">倒序</span>-->
            </div>
            <div class="detail-category-list">
                <ul>
                    <?php if (!empty($list)):foreach ($list as $val):?>
                    <li><span><a href="/book/article?id=<?=$val['id']?>"><?=$val['title']?></a></span> <span></span></li>
                    <?php endforeach;endif;?>
                </ul>
                <div class="page">
                    <a href="<?=((int)$page === 1 ? 'javascript:void();' : '/book?id='.$data['id'].'&page='.($page - 1))?>" class="btn-default btn">上一页</a>
                    <span><?=$page?>/<?=$totalPage?></span>
                    <a href="<?=((int)$page >= (int)$totalPage ? 'javascript:void();' : '/book?id='.$data['id'].'&page='.($page + 1))?>" class="btn-default btn">下一页</a>
                 </div>
            </div>
        </div>

        <div class="detail-module-wrap"><!----></div>
        <div class="detail-module-wrap">
            <div class="Operate" style="display: none;"><img src=""></div>
        </div>
    </div>
    <div data-v-1831b25c="" class="toast hide"></div>
</div>
<!-- jQuery 3 -->
<script src="/dist/plugins/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/dist/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
<script>
    $(function(){
        $('#Header').css('opacity', $(document).scrollTop() /100);
        $('.detail-cata').click(function(){
            $('.detail-category-mask').show();
        });
        $('.detail-category-mask .close').click(function(){
            $('.detail-category-mask').hide();
        });
        $(window).scroll(function(){
            $('#Header').css('opacity', $(document).scrollTop() /100);
        });
        $('.detail-cont-desc').click(function(){
            $('.detail-cont-desc').toggleClass('expand');
        });
    });
</script>
</body>
</html>
