<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title><?= $title ?></title>
    <meta name="keywords" content="<?= $keywords ?>"/>
    <meta name="description" content="<?= $description ?>"/>
    <meta name="renderer" content="webkit">
    <meta name="baidu-site-verification" content="BHWf635LMo" />
    <meta name="baidu-site-verification" content="olOYi3iZmY" />
    <link type="text/css" rel="stylesheet" href="/dist/plugins/bootstrap/dist/css/bootstrap.css" />
    <link type="text/css" rel="stylesheet" href="/dist/css/base.css?v=<?=$version?>" />
    <link type="text/css" rel="stylesheet" href="/dist/css/web.css?v=<?=$version?>" />
    <?php if ('member' === $controllerName && $user):?>
        <link type="text/css" rel="stylesheet" href="/dist/css/member.css?v=<?=$version?>" />
    <?php else:?>
    <link type="text/css" rel="stylesheet" href="/dist/css/web-index.css?v=<?=$version?>" />
    <?php endif;?>
    <script type="text/javascript" src="/dist/plugins/jquery/dist/jquery.js"></script>
</head>
<body>
<script>
    var login = "/member/login";
    var login_a  = "/member/login";
    var register = "/member/register";
    var register_a = "/member/register";
    var is_valid = "{:U('login/is_valid')}";
    var geterror = "{:U('member/geterror')}";
    var url = '{$url}';
</script>
<div class="header">
    <div class="top">
        <div class="kuan">
            <div class="left"><a href="javascript:void(0)" onclick="SetHome(this,'<?=$config['host']?>');">设为首页</a> | <a href="javascript:void(0)" onclick="AddFavorite('<?=$config['host']?>',location.href)">收藏本站</a></div>
            <div class="right yhao">
                <?php if(empty($user)):?>
                    请 <a href="/member/login" id="show_log" class="red">登录</a> 或 <a href="/member/register" id="show_reg">注册</a>
                <?php else:?>
                    欢迎 <span class="red"><?=$user['username']?></span> 回来！ [<a href="/member/info">用户中心</a>] [<a href="/member/logout">退出</a>]
                <?php endif;?>
            </div>
        </div>
    </div>
    <div class="kuan logsear">
        <div class="logo left"><img src="/dist/images/logo.png"></div>
        <div class="search left">
            <form action="/category/search" method="get">
                <span class="select left" id="select">书名</span>
                <dl class="sub">
                    <dd data-value="name">书名</dd>
                    <dd data-value="author">作者</dd>
<!--                    <dd class="border_none">模糊</dd>-->
                </dl>
                <input type="text" name="keywords" value="" class="keywords" autocomplete="off" />
                <input type="hidden" name="searchtype" value="name" id="searchtype" />
                <button type="submit" class="submit"></button>
            </form>
        </div>
    </div>
    <div class="nav">
        <div class="navlist">
            <ul>
                <li><a href="/" class="<?php if (!isset($categoryId))echo 'nav_hover'?>">网站首页</a></li>
                <?php if(!empty($category)):foreach ($category as $key => $val):?>
                <li><a href="/category/index?id=<?=$key?>" class="<?php if(isset($categoryId) && $categoryId == $key)echo 'nav_hover';?>"><?=$val?></a></li>
                <?php endforeach;endif;?>
                <li class="right"><a href="/member/book">我的书架</a></li>
                <li class="right"><a href="/member/applyBook">申请收录</a></li>
            </ul>
        </div>
    </div>
</div>
<?=$this->getContent();?>
<div class="footer">
    <p><?=$config['powerby']?></p>
    <p>Copyright ©2019 <a href="<?=$config['host']?>" title="<?=$config['host_name']?>"><?=$config['host_name']?></a> All Rights Reserved.</p>
    <p><?=$config['record']?></p>
</div>
<div class="bg"></div>
<!--<div class="login-jump" id="login-jump">-->
<!--    <div class="tit">-->
<!--        <em class="close">关闭</em>-->
<!--        <span class="current" tabid="1">登录</span><span tabid="2">注册</span>-->
<!--    </div>-->
<!--    <div class="con">-->
<!--        <div class="tab_log_reg tabpanel" id="lg-jump" style="display: block;">-->
<!--            <h6>注册用户请直接登录</h6>-->
<!--            <form name="login_form" class="jqtransformdone">-->
<!--                <table cellspacing="0" cellpadding="0" border="0" width="100%" class="login_box">-->
<!--                    <tbody><tr>-->
<!--                        <td class="log_reg_tit">账号：</td>-->
<!--                        <td><div class="parentCls"><input name="username" type="text" autocomplete="off"></div></td>-->
<!--                    </tr>-->
<!--                    <tr>-->
<!--                        <td class="log_reg_tit">密码：</td>-->
<!--                        <td><input name="password" type="password"></td>-->
<!--                    </tr>-->
<!--                    </tbody></table>-->
<!--                <div class="tc">-->
<!--                    <button name="login" id="login" type="button" class="button">登录</button>-->
<!--                    <a class="forgot" href="" target="_blank">忘记密码</a>-->
<!--                </div>-->
<!--                <div class="lawer">-->
<!--                    <em class="purity_red fs14 fb">没有账号？</em><a id="reg_a" href="javascript:void(0)">立即注册账号</a>-->
<!--                </div>-->
<!--            </form>-->
<!--        </div>-->
<!--        <div class="tab_log_reg tabpanel" id="rg-jump" style="display: none;">-->
<!--            <form name="register_form">-->
<!--                <table cellspacing="0" cellpadding="0" border="0" width="100%" class="regist_box">-->
<!--                    <tbody><tr>-->
<!--                        <td class="log_reg_tit">账号：</td>-->
<!--                        <td>-->
<!--                            <input name="username" type="text" value="" id="username">-->
<!--                            <p class="emailMessage">只能输入字母，长度6-20位</p>-->
<!--                        </td>-->
<!--                    </tr>-->
<!--                    <tr>-->
<!--                        <td class="log_reg_tit">密码：</td>-->
<!--                        <td>-->
<!--                            <input name="password" type="password" id="password"><em class="passwordSuggestion"></em>-->
<!--                            <p class="passwordMessage">6-16个字符，英文字母(区分大小写)或数字组成。</p>-->
<!--                        </td>-->
<!--                    </tr>-->
<!--                    <tr>-->
<!--                        <td class="log_reg_tit">确认密码：</td>-->
<!--                        <td>-->
<!--                            <input name="repassword" type="password" id="repassword">-->
<!--                        </td>-->
<!--                    </tr>-->
<!--                    </tbody></table>-->
<!--                <div class="tc">-->
<!--                    <button type="button" class="button" id="register">提交</button>-->
<!--                </div>-->
<!--            </form>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<!--<script type="text/javascript" src="/dist/js/email.js"></script>-->
<!--<script type="text/javascript" src="/dist/js/login.js"></script>-->
<script type="text/javascript" src="/dist/js/web.js?v=<?=$version?>"></script>
<div class="right_fixd"><!-- <a href="javascript:void(0);" class="find_error" rel="nofollow">挑错</a> --><a href="javascript:void(0);" id="go_top"></a></div>
<script>
    var _hmt = _hmt || [];
    (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?30c704cbc8165adbabf461d965b9d579";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>
</body>
</html>
