
<!DOCTYPE html>
<html>
<head>
    <title><?= $title ?></title>
    <meta name="keywords" content="<?= $keywords ?>"/>
    <meta name="description" content="<?= $description ?>"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?php if (isset($og) && 1 === (int) $og):?>
    <meta property="og:type" content="novel"/>
    <meta property="og:title" content="<?=$book['book_name']?>"/>
    <meta property="og:image" content="<?=$book['book_img']?>"/>
    <meta property="og:url" content="https://<?=$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];?>"/>
    <meta property="og:description" content="<?=$book['book_intro']?>"/>
    <meta property="og:novel:category" content="<?=$category[$book['book_category']]?>"/>
    <meta property="og:novel:author" content="<?=$book['book_author']?>"/>
    <meta property="og:novel:book_name" content="<?=$book['book_name']?>"/>
    <meta property="og:novel:read_url" content="https://<?=$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];?>"/>
    <meta property="og:novel:status" content="<?=$book['book_state'] == 1 ? '已完结' : '连载中'?>"/>
    <meta property="og:novel:update_time" content="<?=$article['create_at']?>"/>
    <meta property="og:novel:latest_chapter_name" content="<?=$article['title']?>"/>
    <meta property="og:novel:latest_chapter_url" content="https://<?=$_SERVER['HTTP_HOST']?>/book/article?book_id=<?=$book['id']?>&id=<?=$article['id']?>"/>
    <?php endif;?>
    <link href="/dist/plugins/jqweui/dist/lib/weui.min.css" rel="stylesheet" />
    <link href="/dist/plugins/jqweui/dist/css/jquery-weui.css" rel="stylesheet" />
    <link rel="stylesheet" href="/dist/plugins/font-awesome/css/font-awesome.min.css">
    <link href="/dist/css/base.css" rel="stylesheet" />
    <link href="/dist/css/m.css" rel="stylesheet" />
    <script src="/dist/plugins/jqweui/dist/lib/jquery-2.1.4.js"></script>
</head>
<body>
<div class="weui-tab">
    <div class="weui-tab" style="<?php if (isset($mMenu) && 'none' === $mMenu)echo 'height:auto'?>">
        <div class="weui-tab__bd" style="<?php if (!isset($mMenu) || 'none' !== $mMenu)echo 'padding-bottom: 50px'?>">
            <?=$this->getContent()?>
        </div>

        <div class="weui-tabbar" style="<?php if (isset($mMenu) && 'none' === $mMenu)echo 'display:none'?>">
            <a href="/" class="weui-tabbar__item <?php if(!isset($mMenu) || 'home' === $mMenu):echo 'weui-bar__item--on';endif;?>">
                <div class="weui-tabbar__icon">
                    <i class="fa fa-home"></i>
                </div>
                <p class="weui-tabbar__label">首页</p>
            </a>
            <a href="/category/mAll.html" class="weui-tabbar__item <?php if(isset($mMenu) && 'category' === $mMenu):echo 'weui-bar__item--on';endif;?>">
                <div class="weui-tabbar__icon">
                    <i class="fa fa-bars"></i>
                </div>
                <p class="weui-tabbar__label">分类</p>
            </a>
            <a href="/member/book.html" class="weui-tabbar__item <?php if(isset($mMenu) && 'userBook' === $mMenu):echo 'weui-bar__item--on';endif;?>">
                <div class="weui-tabbar__icon">
                    <i class="fa fa-folder"></i>
                </div>
                <p class="weui-tabbar__label">书架</p>
            </a>
            <a href="/member/index.html" class="weui-tabbar__item <?php if(isset($mMenu) && 'member' === $mMenu):echo 'weui-bar__item--on';endif;?>">
                <div class="weui-tabbar__icon">
                    <i class="fa fa-user-circle-o"></i>
                </div>
                <p class="weui-tabbar__label">我的</p>
            </a>
        </div>
    </div>

<script src="/dist/plugins/jqweui/dist/js/jquery-weui.js"></script>
<script src="/dist/js/m.js"></script>
<script>
    var _hmt = _hmt || [];
    (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?f5e17e0a5dd1dc2eb8c85c0a0eda969e";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
    $(function(){
        <?php if (!empty($errorMsg)):?>
        $.toptip('<?=$errorMsg?>', 'error');
        <?php endif;?>
        <?php if (!empty($successMsg)):?>
        $.toptip('<?=$successMsg?>', 'success');
        <?php endif;?>
    });
</script>

</body>
</html>
