<div class="here">当前位置:<a href="/">网站首页</a> &gt; 搜索 <span class='red'><?=$keywords?></span> 的结果
<div class="search_list">
    <div class="result right">
        <ul>
            <?php if (empty($books)):?>
                <li style="border:none;font-size: 36px;line-height: 36px;padding-top: 50px; text-align:center;color:red;">暂无搜索结果</li>
            <?php else:?>
            <?php foreach ($books as $val):?>
                <li><a href="/book/index.html?id=<?=$val['id']?>" target="_blank" title="<?=$val['book_name']?>" class="img"><img src="<?=$val['book_img']?>" width="120" height="150" alt="<?=$val['book_name']?>"/></a><p class="title"><a href="/book/index.html?id=<?=$val['id']?>" target="_blank" title="<?=$val['book_name']?>" class="green"><?=$val['book_name']?></a><span>作者：<?=$val['book_author']?></span></p>
                    <div class="intro">
                        <p>最新章节：<a href="/book/article.html?id=<?=$val['article']['id'] ?? ''?>" target="_blank" title="<?=$val['article']['title'] ?? ''?>"><?=$val['article']['title'] ?? ''?></a><span><?=$val['article']['create_at'] ?? ''?></span></p>
                        <div class="left description"><?=$val['book_intro']?></div>
<!--                        <div class="right anniu">-->
<!--                            <a href="javascript:void(0);" class="btn_tj" onclick="post_recommend({$bo.book_id})">投推荐票</a>-->
<!--                            <a href="javascript:void(0);" onclick="post_rack({$bo.book_id})" class="btn_sj">加入书架</a>-->
<!--                            <a href="{:U('chapter/a', 'book_id='.$bo['book_id'])}" class="btn_sr" target="_blank">开始阅读</a>-->
<!--                        </div>-->
                    </div>
                </li>
                <div class="clear"></div>
            <?php endforeach;endif;?>
        </ul>
        <?php if (!empty($books)):?>
        <div class="page">
            <?=$pageCount?> 条记录 <?=$page?>/<?=$pageTotal?> 页
            <a href="<?php if ($page > 1):echo '?keywords='.$keywords.'&searchtype='.$searchtype.'&page='.($page - 1);else:echo 'javascript:;';endif;?>">上一页</a>
            <a href="<?php if ($page < $pageTotal):echo '?keywords='.$keywords.'&searchtype='.$searchtype.'&page='.($page + 1);else:echo 'javascript:;';endif;?>">下一页</a>
        </div>
        <?php endif;?>
    </div>
    <div class="left lastku">
        <div class="title_bg">月点击榜</div>
        <ul>
            <?php if(!empty($month)):foreach ($month as $key => $val):?>
                <li><em class="<?php switch ($key):case 0:echo 'first';break;case 1:echo 'second';break;case 2:echo 'third';break;endswitch;?>"><?=$key+1?></em><a href="/book/index.html?id=<?=$val['id']?>" title="<?=$val['book_name']?>" target="_blank"><?=$val['book_name']?></a><span><?=$val['book_monthclick']?></span></li>
            <?php endforeach;endif;?>
        </ul>
    </div>
    <div class="left lastku">
        <div class="title_bg">最新免费小说</div>
        <ul>
            <?php if(!empty($newest)):foreach ($newest as $key => $val):?>
                <li>[<a href="/category/index.html?id=<?=$val['book_category']?>" target="_blank" title="<?=$category[$val['book_category']] ?? ''?>"><?=$category[$val['book_category']] ?? ''?></a>] <a href="/book/index.html?id=<?=$val['id']?>" target="_blank" title="<?=$val['book_name']?>"><?=$val['book_name']?></a><span><?=$val['book_author']?></span></li>
            <?php endforeach;endif;?>
        </ul>
    </div>
</div>
<div class="clear"></div>