<div class="weui-search-bar" id="searchBar">
    <form class="weui-search-bar__form" method="get" action="/category/search.html">
        <div class="weui-search-bar__box">
            <i class="weui-icon-search"></i>
            <input type="search" name="keywords" class="weui-search-bar__input" id="searchInput" placeholder="搜索">
            <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
        </div>
        <label class="weui-search-bar__label" id="searchText">
            <i class="weui-icon-search"></i>
            <span>搜索</span>
        </label>
    </form>
    <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
</div>
<div class="weui-tab__bd-item weui-tab__bd-item--active">
    <div class="weui-panel weui-panel_access index-list">
        <div class="weui-panel__hd">最新小说</div>
        <div class="weui-panel__bd">
            <?php if (!empty($data)):foreach ($data as $val): ?>
                <a href="/book?id=<?= $val['id'] ?>" class="weui-media-box weui-media-box_appmsg">
                    <div class="weui-media-box__hd">
                        <img class="weui-media-box__thumb" src="<?= $val['book_img'] ?>">
                    </div>
                    <div class="weui-media-box__bd">
                        <p class="weui-media-box__desc title"><?= $val['book_name'] ?></p>
                        <p class="weui-media-box__desc">作者：<?= $val['book_author'] ?></p>
                        <p class="weui-media-box__desc">摘要：<?= $val['book_intro'] ?></p>
                    </div>
                </a>
            <?php endforeach;endif; ?>
        </div>
    </div>
</div>
