<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="renderer" content="webkit">
<title>温馨提示</title>
<link rel="stylesheet" type="text/css" href="/dist/css/admin.css"/>
<style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }
 </style>
</head>
<body>
<div class="jump">
	<div class="box">
		<div class="ul">
			<h3><?=$message?></h3>
			<p>
			页面自动 <a href="<?=$url?>" id="href">跳转</a> 等待时间： <b id="wait"><?=$waitSecond?></b>
			</p>
		</div>
	</div>
</div>
<script type="text/javascript">
(function(){
var wait = document.getElementById('wait'),href = document.getElementById('href').href;
var interval = setInterval(function(){
	var time = --wait.innerHTML;
	if(time <= 0) {
	    if (href === 'javascript:history.go(-1)') {
            history.go(-1);
        } else {
            location.href = href;
        }
		clearInterval(interval);
	};
}, 1000);
})();
</script>
</body>
</html>