<div class="main">
    <div class="left zztj">
        <h3 class="title_bg">站长推荐</h3>
        <?php if (!empty($recommend)):foreach ($recommend as $val):?>
            <div class="img"><a href="/book?id=<?=$val['id']?>" target="_blank" title="<?=$val['book_name']?>"><img src="<?=$val['book_img']?>" width="105" height="140" alt="<?=$val['book_name']?>" /></a></div>
            <dl>
                <dt><a href="/book?id=<?=$val['id']?>" target="_blank" title="<?=$val['book_name']?>"><?=$val['book_name']?></a><span><?=$val['book_author']?></span></dt>
                <dd>&nbsp;&nbsp;&nbsp;&nbsp;<?=mb_substr($val['book_intro'], 0, 80)?>...</dd>
            </dl>
        <?php endforeach;endif;?>
    </div>
    <div class="right gg">
        <h3 class="title_bg">公告</h3>
        <ul>
            <p><?=$config['notice']?></p>
        </ul>
    </div>
    <div class="clear"></div>
    <div class="mbox">
        <div class="boxlist">
            <a class="LeftBotton" onmousedown="ISL_GoUp_1()" onmouseup="ISL_StopUp_1()" onmouseout="ISL_StopUp_1()" href="javascript:void(0);" target="_self"></a>
            <div id="ISL_Cont_1" class="pcont">
                <div class="ScrCont">
                    <div id="List1_1">
                        <ul>
                            <?php if (!empty($week)):foreach ($week as $val):?>
                                <li><a href="/book?id=<?=$val['id']?>" target="_blank" title="<?=$val['book_name']?>"><img src="<?=$val['book_img']?>" width="105" height="140" alt="<?=$val['book_name']?>" /></a><span class="bookname"><a href="/book?id=<?=$val['id']?>" target="_blank" title="<?=$val['book_name']?>"><?=$val['book_name']?></a></span><span class="author"><?=$val['book_author']?></span></li>
                            <?php endforeach;endif;?>
                        </ul>
                    </div>
                    <div id="List2_1"></div>
                </div>
            </div>
            <a class="RightBotton" onmousedown="ISL_GoDown_1()" onmouseup="ISL_StopDown_1()" onmouseout="ISL_StopDown_1()" href="javascript:void(0);" target="_self"></a>
        </div>
    </div>
    <div class="clear"></div>
    <div class="tab">
        <div class="tab_title title_bg">
            <?php if(!empty($category)):$i=0;foreach ($category as $key => $val):?>
                <span <?php if(0 === $i)echo 'class="hover"'?> onmouseover="setTab(this,<?=$i+1?>)"><?=$val?></span>
                <?php if(0 === $i)echo '<b></b>'?>
            <?php $i++;endforeach;endif;?>
        </div>
        <?php if(!empty($category)):$i=0;foreach ($category as $key => $val):?>
            <div id="tab_<?=$i+1?>" class="tab_content <?php if(0 === $i)echo 'block'?>">
                <?php if(!empty($categoryBooks[$key]['img_book'])):foreach ($categoryBooks[$key]['img_book'] as $v):?>
                    <div class="tj">
                        <div class="img"><a href="/book?id=<?=$v['id']?>" target="_blank" title="<?=$v['book_name']?>"><img src="<?=$v['book_img']?>" width="84" height="112" alt="<?=$v['book_name']?>" /></a></div>
                        <dl>
                            <dt><a href="/book?id=<?=$v['id']?>" target="_blank" title="<?=$v['book_name']?>"><?=$v['book_name']?></a><span><?=$v['book_author']?></span></dt>
                            <dd>&nbsp;&nbsp;&nbsp;&nbsp;<?=mb_substr($v['book_intro'], 0, 80)?>...</dd>
                        </dl>
                    </div>
                    <?php endforeach;endif;?>
                <div class="clear"></div>
                <ul>
                    <?php if(!empty($categoryBooks[$key]['list_book'])):foreach ($categoryBooks[$key]['list_book'] as $kk => $vv):?>
                        <li <?php if (29 === $kk)echo 'class="border_none"'?>><a href="/book?id=<?=$vv['id']?>" target="_blank" title="<?=$vv['book_name']?>"><?=$vv['book_name']?></a>/<?=$vv['book_author']?></li>
                    <?php endforeach;endif;?>
                </ul>
            </div>
        <?php $i++;endforeach;endif;?>
    </div>
    <div class="clear"></div>
<!--    <div class="left lastarticle">-->
<!--        <div class="title_bg"><span class="last_hover">最近更新小说列表</span><b></b></div>-->
<!--        <ul>-->
<!--            <volist name="lastarticle" id="la">-->
<!--                <li><span class="s1">[<a href="{:U('sort/a','sort_id='.$la['sort_id'])}" title="{$la.sort_name}" target="_blank">{$la.sort_name}</a>]</span><span class="s2"><a href="{:U('book/a','book_id='.$la['book_id'])}" target="_blank" title="{$la.book_name}">{$la.book_name}</a></span><span class="s3"><a href="{:U('article/a','article_id='.$la['article_id'])}" target="_blank" title="{$la.article_title}">{$la.article_title}</a></span><span class="s4">{$la.book_author}</span><span class="s5">{$la.article_addtime|date='m-d',###}</span></li>-->
<!--            </volist>-->
<!--        </ul>-->
<!--    </div>-->
<!--    <div class="right lastku">-->
<!--        <div class="title_bg">月推荐<span class="more"><a href="javascript:;">MORE</a></span></div>-->
<!--        <ul>-->
<!--            --><?php //if(!empty($month)):foreach ($month as $key => $val):?>
<!--                <li><em class="--><?php //switch ($key):case 0:echo 'first';break;case 1:echo 'second';break;case 2:echo 'third';break;endswitch;?><!--">--><?//=$key+1?><!--</em><a href="/book?id=--><?//=$val['id']?><!--" title="--><?//=$val['book_name']?><!--" target="_blank">--><?//=$val['book_name']?><!--</a><span>--><?//=$val['book_monthclick']?><!--</span></li>-->
<!--            --><?php //endforeach;endif;?>
<!--        </ul>-->
<!--    </div>-->
<!--    <div class="right lastku">-->
<!--        <div class="title_bg">最新入库小说</div>-->
<!--        <ul>-->
<!--            --><?php //if(!empty($newest)):foreach ($newest as $key => $val):?>
<!--                <li>[<a href="/category?id=--><?//=$val['book_category']?><!--" target="_blank" title="--><?//=$category[$val['book_category']] ?? ''?><!--">--><?//=$category[$val['book_category']] ?? ''?><!--</a>] <a href="/book/?id=--><?//=$val['id']?><!--" target="_blank" title="--><?//=$val['book_name']?><!--">--><?//=$val['book_name']?><!--</a><span>--><?//=$val['book_author']?><!--</span></li>-->
<!--            --><?php //endforeach;endif;?>
<!--        </ul>-->
<!--    </div>-->
</div>
<div class="clear"></div>

<script type="text/javascript" src="/dist/js/roll.js"></script>
<script type="text/javascript">
    function setTab(obj,id){
        $(".hover").removeClass('hover');
        $(obj).addClass('hover');
        $(".block").removeClass('block');
        $("#tab_"+id).addClass('block');
    }
</script>
<script type="text/javascript">picrun_ini()</script>
