<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $title ?></title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="/dist/plugins/jqweui/dist/lib/weui.min.css" rel="stylesheet" />
    <link href="/dist/plugins/jqweui/dist/css/jquery-weui.css" rel="stylesheet" />
    <link href="/dist/css/base.css" rel="stylesheet" />
    <link href="/dist/css/wap.css" rel="stylesheet" />
</head>
<body class="wap">

<div class="weui-flex nav-top" style="opacity:1">
    <div class="weui-flex__item"></div>
    <div class="weui-flex__item title">小说列表</div>
    <div class="weui-flex__item member"><span class="green loginAlert">登录</span> / <span class="green registerAlert">注册</span></div>
</div>
<div class="book-list">
    <?php if (!empty($data)):foreach ($data as $val):?>
        <div class="weui-panel weui-panel_access book-info">
            <div class="weui-panel__bd">
                <a href="/book?id=<?=$val['id']?>" class="weui-media-box weui-media-box_appmsg">
                    <div class="weui-media-box__hd">
                        <img class="weui-media-box__thumb" src="<?=$val['book_img']?>">
                    </div>
                    <div class="weui-media-box__bd">
                        <p class="weui-media-box__desc title"><?=$val['book_name']?></p>
                        <p class="weui-media-box__desc">作者：<?=$val['book_author']?></p>
                        <p class="weui-media-box__desc">摘要：<?=$val['book_intro']?></p>
                    </div>
                </a>
            </div>
        </div>
    <?php endforeach;endif;?>
</div>
<script src="/dist/plugins/jqweui/dist/lib/jquery-2.1.4.js"></script>
<script src="/dist/plugins/jqweui/dist/js/jquery-weui.js"></script>
<script src="/dist/js/wap.js?version=<?=$version?>"></script>
<script>
    $(function () {
        let isLogin = localStorage.getItem('token') != null;
        if (!isLogin) {
            $('.nav-top .member').html('<span class="green loginAlert">登录</span> / <span class="green registerAlert">注册</span>');
        } else {
            getUserInfo();
        }
        $('.nav-top').on('click', '.loginAlert', function () {
            login();
        });
        $('.nav-top').on('click', '.registerAlert', function () {
            register();
        });
    });
</script>
</body>
</html>
