<link href="/dist/css/m.article.css" rel="stylesheet" />
<div id="read">
    <div class="header">
        <h1><?=$article['title']?></h1>
<!--        <span>加入书架</span>-->
    </div>
    <section class="content">
        <article class="chapterContent">
            <section class="chapter-list" data-id="<?=$article['id']?>">
                <h2><?=$article['title']?></h2>
                <div class="readContent"><?=$article['content']?></div>
            </section>

        </article>
        <div class="loadNext" data-book="<?=$book['id']?>" data-id="<?=$nextId?>">
            <a href="javascript:;">加载下一章</a>
        </div>
    </section>
<!--    <div class="mu">-->
<!--        <div class="prev-mu"></div>-->
<!--        <div class="menu-mu"></div>-->
<!--        <div class="next-mu"></div>-->
<!--    </div>-->
    <div class="tool hidden">
        <header class="tool-header">
            <a href="javascript:history.go(-1)" class="back"><i class="fa fa-chevron-left"></i></a>
            <h3 class="book-name"><?=$book['book_name']?></h3>
        </header>
        <div class="stylePanel hidden">
            <div class="font-setting">
                <button class="font-jian">
                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEkAAAAnCAMAAAB0U5XEAAAAZlBMVEUAAABVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUswj/8AAAAIXRSTlMABNgz9Yae62wpjoEZxrF4WkA5DgndzbdSSRLjvqeUYh/fdWZHAAABVUlEQVRIx62W65KCMAyFucsdRAQVRM77v+SmZWRZJDOm3e9PKZQz7UmaibMjS4nGsecMRe/YE0EzWws9Amgya6UYC4Nrq9SRSqT2dbcU8kEkyqvyH/wudPyC3Eroos71ctwrDZWV0ktt5kLZSePVyvNC+U3jDOJsIZSsAiM9PC2UJgCeo6jVMR/GQu1pNbpV1sfGSvUm+JHeninjJiEbEI2N37f3zNNhNCMEcFqTqFpSywRX+Z2u0xzGnt9AJL/znqYds9Y7Itn+WewiCf9YCXu2a2d9mn12TQZK2YfDk3rTHnt6xPvb8BF1H7rESLmDKMM/BNo5KSUYEqFQHoAhFSpVYFBZL2Ap3IW/JwZRy5uB+vgCjSKlJ5M6qfZc2gxEXKEJJc0AW9Y6oeceW2rjpfp9SwOi4s/di5qBIOdjgVzSDJTcfWTaMrkX7sC0CPL4ZPi6LfsBpg82k4bZ+2QAAAAASUVORK5CYII=">
                </button>
                <button class="font-jia">
                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEkAAAAnCAMAAAB0U5XEAAAAaVBMVEUAAABVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVXYkTobAAAAInRSTlMAzTPYDYYI9Oj5KqCOOt3CsoFfUxl4bkkgD7inmpRoQRPu4kDDzQAAAWNJREFUSMelluuSgjAMRissyP0mN0WEzfs/5CZ1oCtYhrTnh9AZOdivTY3YUCZIKuxJgXgIe2KQ9Nai+xUkpbWphTeBtemClph+V2cpcgCJKKvC0vRERy4m/AxrK5FP86qEyPDSWJkqNFx93J14zezzxmsPyHTugR/xhYgEslByvBksTOM6qYoyn41N/i8FraJvjU2VXHy1HVxjU/5vQ6YyMr5J5X1bRhkto6HJo8L1l1FDW+tuZPIDAEjWYQ3Iy8h0k8Wrxg8cXjQCdyEEWO8j3ZPS7Hw3wR713V7OZru7RgNTuUt4lOXMz4nyjvenXsU2dYAU3gdUMTnbVICGiGmqQ50pYZoa0BH4PFNGkThbWlmJLNOklmlXQDnLNGi2TgJIzzDNlPdTd7B7B6bIcfbNQKp5J2V+Gld71L4zZzRf2r/cOWS1CPFBGzAAUjOaL+17O05b9jrMItC0CPz1KeF0W/YHtdo+HQ5Fp0oAAAAASUVORK5CYII=">
                </button>
            </div>
            <div class="themeConfig">
                <button class="themeItem" data-theme="theme-default" style="background-color: #c4b395; color: rgb(170,127,87);"><span>默认</span></button>
                <button class="themeItem" data-theme="theme-white" style="background-color:#ffffff; color: rgb(51, 51, 51);"><span>白色</span></button>
                <button class="themeItem" data-theme="theme-green" style="background-color: #dcecd2; color: rgb(54, 132, 132);"><span>绿色</span></button>
                <button class="themeItem" data-theme="theme-pink" style="background-color: #f4e6e1; color: rgb(177, 108, 114);"><span>粉色</span></button>
            </div>
        </div>
        <footer class="tool-footer">
            <div class="group">
                <a href="/" class="tool-footer-menu">
                    <div class="weui-tabbar__icon">
                        <i class="fa fa-home"></i>
                    </div>
                    <p class="weui-tabbar__label">首页</p>
                </a>
                <a href="/book?id=<?=$book['id']?>" class="tool-footer-menu">
                    <div class="weui-tabbar__icon">
                        <i class="fa fa-bars"></i>
                    </div>
                    <p class="weui-tabbar__label">目录</p>
                </a>
                <a href="javascript:;" class="tool-footer-menu night">
                    <div class="weui-tabbar__icon">
                        <i class="fa fa-moon-o"></i>
                    </div>
                    <p class="weui-tabbar__label">夜间</p>
                </a>
                <a href="javascript:;" class="tool-footer-menu setting">
                    <div class="weui-tabbar__icon">
                        <i class="fa fa-cog"></i>
                    </div>
                    <p class="weui-tabbar__label">设置</p>
                </a>
            </div>
        </footer>
    </div>
</div>
<script>
    var bookId = <?=$book['id']?>;
    var articleId = <?=$article['id']?>;
    setTimeout(function () {
        $.post('/book/userBook', {"book_id":<?=$article['book_id']?>,"id":<?=$article['id']?>});
    }, 5000);
</script>
<script src="/dist/js/m.article.js"></script>