<div class="weui-flex nav-top">
    <div class="weui-flex__item"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADoAAABmCAMAAACtKXKWAAAAn1BMVEUAAADm5uZERER3d3eHh4c9PT0zMzNAQEA2Njbw8PD7+/tPT09GRkb9/f2rq6uQkJBLS0v09PTr6+vp6enh4eHc3NzT09PPz8/ExMS4uLidnZ2CgoJqampfX19bW1tTU1M7Ozv29vbX19dmZmY9PT1XV1f4+Pj39/fJycm+vr6ysrKkpKSXl5eIiIh7e3t2dnZ1dXVvb285OTlWVlbZ2dnTs/viAAAABnRSTlMA/vz8/PzlztqAAAABjklEQVRYw9WY127CQBBFjUnWDVzo1abY9A7//21RlISd12NFC77vR7Lg7p7ZsXiaYZpn0dziSZbqO0GCSS9VP/mgZDtTv4kh2YnVX2xGLhrqmToi+44mnRohBzNB9gg5dDXZ6BIyFGSAvnakdIoWISNBTj1S27EgJ6S+/lmQFx+Q64kgx01S+KkgIwukVQhyRMhaIMiQkF1ReHdIyJ4o/GxAyE0uCt8n5PamSXtByJ0ofNwh5F7pZG1CHgSZeoQ8CnKZkMKfBHldAXJ1FeTJZ27QOUI36BygG3T2Jd2g3B1yg63J27asG/LN27tBVdYNa0D6F0GeSeHnr3DD/T/c4L69G2oOcoNMXRT+YaHY0g0sn8+jAtwAUPDB/GcCCgV/DqwEL6KB+oNDh486v2BMXGv8MuVXOBcH15UJSXI184GAjyF8+DEycvFBj4+XfKjlo7SJAZ4/G/hjhT+R+MOMPQerbRVFrVIYtApfafBFCl/fmLfKnVrFrbZVHPjND7z45OtWvuTlq2W+0C6/Rv8CppA3o4Rd7ncAAAAASUVORK5CYII=" class="back"></div>
    <div class="weui-flex__item title"><?=$book['book_name']?></div>
    <div class="weui-flex__item home"><a href="/"><i class="fa fa-home"></i></a></div>
</div>
<div class="weui-panel weui-panel_access book-info">
    <div class="weui-panel__hd"><?=$book['book_name']?></div>
    <div class="weui-panel__bd">
        <a href="javascript:void(0);" class="weui-media-box weui-media-box_appmsg">
            <div class="weui-media-box__hd">
                <img class="weui-media-box__thumb" src="<?=$book['book_img']?>">
            </div>
            <div class="weui-media-box__bd">
                <p class="weui-media-box__desc">作者：<?=$book['book_author']?></p>
                <p class="weui-media-box__desc">状态：<?php echo 1 === (int)$book['book_state'] ? '完本' : '连载'?></p>
                <p class="weui-media-box__desc">字数：约<?=round($book['book_wordsnumber']/10000, 2)?>万</p>
            </div>
        </a>
    </div>
    <div class="weui-form-preview__ft">
        <a class="weui-form-preview__btn weui-form-preview__btn_default add-userBook" data-id="<?=$book['id']?>" <?=empty($userBook) ? '' : 'disabled'?> href="javascript:"><?=empty($userBook) ? '加入书架' : '已在书架'?></a>
        <a class="weui-form-preview__btn weui-form-preview__btn_primary" href="/book/article?book_id=<?=$book['id']?>&id=<?=$userBook['article_id'] ?? 0?>">开始阅读</a>
    </div>
</div>
<div class="weui-panel weui-panel_access book-history">
    <div class="weui-panel__bd">
        <div class="weui-media-box__bd">
            <p>阅读章节：<span><?php if (empty($userBook) || empty($userBook['article_id'])):echo '您还未阅读本小说';else:echo '<a href="/book/article?id='.$userBook['article_id'].'&book_id='.$userBook['book_id'].'">'.$userBook['article_title'].'</a>';endif;?></span></p>
        </div>
    </div>
</div>
<div class="weui-panel weui-panel_access book-intro">
    <div class="weui-panel__bd">
        <div class="weui-media-box__bd">
            <p><?=$book['book_intro']?></p>
        </div>
    </div>
</div>
<div class="weui-panel weui-panel_access chapter-list">
    <div class="weui-cells article-list">
        <?php foreach ($list as $val):?>
        <a class="weui-cell weui-cell_access" href="/book/article?id=<?=$val['id']?>&book_id=<?=$book['id']?>">
            <div class="weui-cell__bd">
                <p><?=$val['title']?></p>
            </div>
            <div class="weui-cell__ft">
            </div>
        </a>
        <?php endforeach;?>
    </div>
</div>
<div class="button_sp_area page" style="text-align: center;">
    <a href="<?=((int)$page === 1 ? 'javascript:;' : '/book?id='.$book['id'].'&page='.($page - 1))?>" class="weui-btn weui-btn_mini weui-btn_plain-primary <?=(int)$page === 1 ? 'weui-btn_disabled' : ''?>">上一页</a>
    <select class="weui-btn weui-btn_plain-default" id="pageChange">
        <?php for ($i=1;$i<=$totalPage;$i++):?>
            <option value="<?=$i?>" <?=$i === (int)$page ? 'selected="selected"' : ''?>><?=$i.'/'.$totalPage?></option>
        <?php endfor;?>
    </select>
    <a href="<?=((int)$page >= (int)$totalPage ? 'javascript:;' : '/book?id='.$book['id'].'&page='.($page + 1))?>" class="weui-btn weui-btn_mini weui-btn_plain-primary <?=(int)$page >= (int)$totalPage ? 'weui-btn_disabled' : ''?>">下一页</a>
</div>

<script>
    $(function(){
        let isLogin = localStorage.getItem('token') != null;
        $('.book-intro').click(function () {
            $(this).toggleClass('expand');
        });
        $('#pageChange').change(function(){
            window.location.href = '/book?id='+<?=$book['id']?>+'&page='+$(this).val();
        });
        // $(window).scroll(function(){
        //     $('.nav-top').css('opacity', $(document).scrollTop() /100);
        // });
        // $('.nav-top').css('opacity', $(document).scrollTop() /100);
        // if (!isLogin) {
        //     $('.nav-top .member').html('<span class="green loginAlert">登录</span> / <span class="green registerAlert">注册</span>');
        // } else {
        //     getUserInfo();
        // }
        $('.nav-top').on('click', '.loginAlert', function () {
            login();
        });
        $('.nav-top').on('click', '.registerAlert', function () {
            register();
        });
        <?php if (empty($user)):?>
        let readHistory = localStorage.getItem('book_<?=$book['id']?>');
        if (readHistory) {
            $('.book-history span').html(readHistory);
        }
        <?php endif;?>
    });
</script>
