<div class="here">当前位置:<a href="/">网站首页</a> > 申请收录</div>
<div class="member">
    <div class="applyBook">
        <form class="form-horizontal" method="post">
            <div class="form-group">
                <label for="book_name" class="col-sm-2 control-label">小说名称</label>
                <div class="col-sm-10">
                    <input type="text" name="book_name" class="form-control" id="book_name" placeholder="小说名称">
                </div>
            </div>
            <div class="form-group">
                <label for="author" class="col-sm-2 control-label">作者</label>
                <div class="col-sm-10">
                    <input type="text" name="author" class="form-control" id="author" placeholder="作者">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">提交</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="clear"></div>