<div class="here">当前位置:<a href="/">网站首页</a> &gt; 会员中心 > 我的书架</div>
<div class="member">
    <div class="member_menu left">
        <h3>会员中心</h3>
        <dl>
            <dt>会员设置</dt>
            <dd class="info"><a href="/member/info">基本资料</a></dd>
            <dd class="password"><a href="/member/password">修改密码</a></dd>
            <dt>工具箱</dt>
            <dd class="book"><a href="/member/book">我的书架</a></dd>
        </dl>
    </div>
    <div class="member_body right">
        <table width="769" border="0" bgcolor="#ccc" cellpadding="0" cellspacing="1" class="rack">
            <tr>
                <th>小说名称</th>
                <th>最新章节</th>
                <th>阅读记录</th>
                <th>更新时间</th>
                <th>移除</th>
            </tr>
            <?php if (!empty($userBooks)):foreach ($userBooks as $val):?>
            <volist name="rack" id="ra">
                <tr>
                    <td>《<a href="/book?id=<?=$val['book_id']?>"><?=$val['book_name']?></a>》</td>
                    <td><a href="/book/article?book_id=<?=$val['book_id']?>&id=<?=$val['last_id']?>"><?=$val['last_title']?></a></td>
                    <td><a href="/book/article?book_id=<?=$val['book_id']?>&id=<?=$val['article_id']?>"><?=$val['article_title']?></a></td>
                    <td width="130"><?=$val['last_time']?></td>
                    <td width="40"><a href="javascript:void(0);" onclick="delsure(<?=$val['id']?>);">移除</a></td>
                </tr>
            </volist>
            <?php endforeach;?>
            <?php else:?>
            <tr><td colspan="5">暂无数据</td></tr>
            <?php endif;?>
        </table>
    </div>
</div>
<div class="clear"></div>
<script>
    $(function () {
        $('.member_menu').find('.<?=$menuHover?>').addClass('menu_hover').find('a').attr('href', 'javascript:;');
    });
</script>