<div class="here">当前位置:<a href="/">网站首页</a> &gt; 会员中心 > 修改密码</div>
<div class="member">
    <div class="member_menu left">
        <h3>会员中心</h3>
        <dl>
            <dt>会员设置</dt>
            <dd class="info"><a href="/member/info">基本资料</a></dd>
            <dd class="password"><a href="/member/password">修改密码</a></dd>
            <dt>工具箱</dt>
            <dd class="book"><a href="/member/book">我的书架</a></dd>
        </dl>
    </div>
    <div class="member_body right">
        <form action="" method="post">
        <table width="769" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <th width="150" scope="row" class="text_right">原密码：</th>
                <td><input type="password" name="old_password" value="" id="old_password" /> </td>
            </tr>
            <tr>
                <th scope="row" class="text_right">新密码：</th>
                <td><input type="password" name="password" value="" id="password" /></td>
            </tr>
            <tr>
                <th scope="row" class="text_right">确认密码：</th>
                <td colspan="2"><input type="password" name="repassword" value="" id="repassword" /></td>
            </tr>
            <tr>
                <th colspan="2" class="border_none"><button type="submit" class="button" id="edit_user">确认修改</button>　　　<button type="reset" class="button">重置</button></th>
                <td class="border_none"></td>
            </tr>
        </table>
        </form>
    </div>
</div>
<div class="clear"></div>
<script>
    $(function () {
        $('.member_menu').find('.<?=$menuHover?>').addClass('menu_hover').find('a').attr('href', 'javascript:;');
    });
</script>